# Generated by Django 2.2.10 on 2021-08-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizitem',
            old_name='title',
            new_name='text',
        ),
        migrations.AddField(
            model_name='quizitem',
            name='answer_type',
            field=models.CharField(choices=[('text', 'ответ текстом'), ('radio', 'о одного варианта'), ('checkbox', 'твет с выбором нескольких вариантов')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quiz.Quiz'),
        ),
    ]
