# Generated by Django 2.2.10 on 2021-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210821_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizitem',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
