# Generated by Django 2.2.10 on 2021-08-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210821_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.QuizItem')),
            ],
        ),
    ]
