# Generated by Django 2.2.10 on 2021-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizparticipation',
            name='quiz_item',
        ),
        migrations.AddField(
            model_name='quizparticipation',
            name='quiz_item',
            field=models.ManyToManyField(to='quiz.QuizItem'),
        ),
    ]
