# Generated by Django 2.2.10 on 2021-08-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210821_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizParticipation',
        ),
    ]
