# Generated by Django 2.2.10 on 2021-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_delete_quizparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizParticipation',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_item', models.ManyToManyField(to='quiz.QuizItem')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
