# Generated by Django 2.2.10 on 2021-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizparticipation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizparticipation',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
