# Generated by Django 2.2.10 on 2021-08-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210821_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizparticipation',
            name='quiz_item',
            field=models.ManyToManyField(blank=True, to='quiz.QuizItem'),
        ),
    ]
