# Generated by Django 3.1.2 on 2020-10-24 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('F', 'Физическое лицо'), ('U', 'Юридическое лицо')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('brd_date', models.DateField()),
                ('dep_code', models.CharField(max_length=20)),
                ('issued_by', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('front_image', models.FileField(upload_to='passport_image')),
                ('back_image', models.FileField(upload_to='passport_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
