# Generated by Django 3.1.2 on 2020-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201024_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms',
            field=models.ManyToManyField(related_name='terms', to='app.Terms'),
        ),
    ]
