# Generated by Django 3.1.2 on 2020-10-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201024_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(choices=[('F', 'Физическое лицо'), ('U', 'Юридическое лицо')], max_length=20, null=True),
        ),
    ]
