# Generated by Django 3.1.2 on 2020-10-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201024_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='qualification_icons')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualific', to='app.qualification'),
        ),
    ]
