# Generated by Django 3.1.2 on 2020-10-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userprofile_is_qualificated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.qualification'),
        ),
    ]
