# Generated by Django 3.1.2 on 2020-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201024_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_qualificated',
            new_name='is_qualified',
        ),
    ]
